name: stochastic-quantization
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.*
  - notebook=7.*
  - ipywidgets=8.*
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - pytorch-cuda=12.4
  - matplotlib=3.*
  - scikit-learn=1.5.*
  - tqdm=4.*