# Manages building, testing, and cleaning the code as well as running the code
# to generate the results and figures for the paper.

# Run all steps to generate the final figures.
all:
	@echo "TODO: Create build, test and run steps"

